# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Whisper of Koori
email: 166861631@qq.com
description: > # this means to ignore newlines until "baseurl:"
一个用来絮絮叨叨的地方，话题包含动漫、图书、电影、追星，能力允许会记录专业上的小科普
baseurl: "Sadiehatsuki.github.io" # the subpath of your site, e.g. /blog
lang: "Chinese"
url: "Sadiehatsuki.github.io" # the base hostname & protocol for your site
twitter_username: Sadie_こおり
github_username:  Sadiehatsuki
weibo_username: Sadie_土撥鼠_koori

# Build settings
markdown: 小书匠
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'
